package com.beshara.csc;

import javax.xml.ws.Holder;

import kw.gov.moi.common.v1.moiheader.MoiHeader;
import kw.gov.moi.services.criminalevidenceservice.v1.types.MoiGoodBehaviorCertificateDataIn;
import kw.gov.moi.services.criminalevidenceservice.v1.types.MoiGoodBehaviorCertificateDataOut;


// This source file is generated by Oracle tools.
// Contents may be subject to change.
// For reporting problems, use the following:
// Generated by Oracle JDeveloper 11g Release 2 11.1.2.4.0.6436

public class CriminalEvidenceBindingQSPortClient {
    public String crmWebService(Long civilID){
            CriminalEvidenceBindingQSService criminalEvidenceBindingQSService = new CriminalEvidenceBindingQSService();

//            SecurityPoliciesFeature securityFeatures =
//                new SecurityPoliciesFeature(new String[] { "oracle/no_authentication_client_policy" });
            MoiGoodBehaviorCertificateDataOut out=null;
                try {
            CriminalEvidenceService criminalEvidenceService =
                criminalEvidenceBindingQSService.getCriminalEvidenceBindingQSPort();
            MoiGoodBehaviorCertificateDataIn inquireGoodBehaviorCertificateDataRequestParam =
                new MoiGoodBehaviorCertificateDataIn();
            inquireGoodBehaviorCertificateDataRequestParam.setCivilId(civilID.toString());
            Holder<MoiHeader> moiHeader = new Holder<MoiHeader>();
            moiHeader.value = new MoiHeader();
            // Add your code to call the desired methods.
            
                 out=criminalEvidenceService.inquireGoodBehaviorCertificateData(moiHeader,
                                                                           inquireGoodBehaviorCertificateDataRequestParam);
               
                    
            } catch (Exception e) {
                e.printStackTrace();
                return "0";
            }
        
           return out.getErrorCode();
        }
//    public static void main(String[] args) {
//        CriminalEvidenceBindingQSService criminalEvidenceBindingQSService = new CriminalEvidenceBindingQSService();
//
//        // Configure security feature
//        SecurityPoliciesFeature securityFeatures =
//            new SecurityPoliciesFeature(new String[] { "oracle/no_authentication_client_policy" });
//        CriminalEvidenceService criminalEvidenceService =
//            criminalEvidenceBindingQSService.getCriminalEvidenceBindingQSPort(securityFeatures);
//        MoiGoodBehaviorCertificateDataIn inquireGoodBehaviorCertificateDataRequestParam =
//            new MoiGoodBehaviorCertificateDataIn();
//        inquireGoodBehaviorCertificateDataRequestParam.setCivilId("290091800123");
//        Holder<MoiHeader> moiHeader = new Holder<MoiHeader>();
//        moiHeader.value = new MoiHeader();
//        // Add your code to call the desired methods.
//        try {
//            MoiGoodBehaviorCertificateDataOut out=criminalEvidenceService.inquireGoodBehaviorCertificateData(moiHeader,
//                                                                       inquireGoodBehaviorCertificateDataRequestParam);
//            System.out.println(out.getCivilId());
//            System.out.println(out.getErrorCode());
//            System.out.println(out.getErrorMessage());
//                
//        } catch (InquireGoodBehaviorCertificateDataFaultMsg e) {
//            e.printStackTrace();
//        } catch (Throwable t) {
//            t.printStackTrace();
//        }
//        // Add your code to call the desired methods.
//    }
}
