
package com.beshara.csc;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * OSB Service
 * 
 * This class was generated by the JAX-WS RI.
 * Oracle JAX-WS 2.1.5
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "CriminalEvidenceBindingQSService", targetNamespace = "http://www.moi.gov.kw/Services/CriminalEvidenceService/V1/Definitions", wsdlLocation = "http://sbservices.csc.gov.kw/CSCServices/ProxyServices/MOIGBC_ProxySrv?wsdl#%7Bhttp%3A%2F%2Fwww.moi.gov.kw%2FServices%2FCriminalEvidenceService%2FV1%2FDefinitions%7DCriminalEvidenceBindingQSService")
public class CriminalEvidenceBindingQSService
    extends Service
{

    private final static URL CRIMINALEVIDENCEBINDINGQSSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(com.beshara.csc.CriminalEvidenceBindingQSService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = com.beshara.csc.CriminalEvidenceBindingQSService.class.getResource(".");
            url = new URL(baseUrl, "http://sbservices.csc.gov.kw/CSCServices/ProxyServices/MOIGBC_ProxySrv?wsdl#%7Bhttp%3A%2F%2Fwww.moi.gov.kw%2FServices%2FCriminalEvidenceService%2FV1%2FDefinitions%7DCriminalEvidenceBindingQSService");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://sbservices.csc.gov.kw/CSCServices/ProxyServices/MOIGBC_ProxySrv?wsdl#%7Bhttp%3A%2F%2Fwww.moi.gov.kw%2FServices%2FCriminalEvidenceService%2FV1%2FDefinitions%7DCriminalEvidenceBindingQSService', retrying as a local file");
            logger.warning(e.getMessage());
        }
        CRIMINALEVIDENCEBINDINGQSSERVICE_WSDL_LOCATION = url;
    }

    public CriminalEvidenceBindingQSService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CriminalEvidenceBindingQSService() {
        super(CRIMINALEVIDENCEBINDINGQSSERVICE_WSDL_LOCATION, new QName("http://www.moi.gov.kw/Services/CriminalEvidenceService/V1/Definitions", "CriminalEvidenceBindingQSService"));
    }

    /**
     * 
     * @return
     *     returns CriminalEvidenceService
     */
    @WebEndpoint(name = "CriminalEvidenceBindingQSPort")
    public CriminalEvidenceService getCriminalEvidenceBindingQSPort() {
        return super.getPort(new QName("http://www.moi.gov.kw/Services/CriminalEvidenceService/V1/Definitions", "CriminalEvidenceBindingQSPort"), CriminalEvidenceService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CriminalEvidenceService
     */
    @WebEndpoint(name = "CriminalEvidenceBindingQSPort")
    public CriminalEvidenceService getCriminalEvidenceBindingQSPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.moi.gov.kw/Services/CriminalEvidenceService/V1/Definitions", "CriminalEvidenceBindingQSPort"), CriminalEvidenceService.class, features);
    }

}
