package com.beshara.csc.hr.emp.business.shared.exception;

import com.beshara.csc.sharedutils.business.exception.SharedApplicationException;

import javax.ejb.ApplicationException;

public class BeenAccreditationPleaseCompleteTheDataCandidate extends SharedApplicationException {


    /**
     *
     * @since 26/11/2015
     * @updatedBy TechnicalTeam [A.Agamy]
     * @Note added new constractors to pass exception
     * constructors generated by ExceptionHandlerProcessor
     */
    @SuppressWarnings("compatibility:-4485906751177687898")
    private static final long serialVersionUID = 1L;
    public static final String DEF_MSG = "BeenAccreditationPleaseCompleteTheDataCandidate";
    public static final String MSG_KEY = "BeenAccreditationPleaseCompleteTheDataCandidate";
    public static final String BDL_KEY = "BeenAccreditationPleaseCompleteTheDataCandidate";

    public BeenAccreditationPleaseCompleteTheDataCandidate(String message, Throwable e, String bundleKey,
                                                           String messageKey) {
        super(message, e, bundleKey, messageKey);
    }


    public BeenAccreditationPleaseCompleteTheDataCandidate(String message, Throwable e, String messageKey) {
        super(message, e, BDL_KEY, messageKey);
    }


    public BeenAccreditationPleaseCompleteTheDataCandidate(String message, Throwable e) {
        super(message, e, BDL_KEY, MSG_KEY);
    }


    public BeenAccreditationPleaseCompleteTheDataCandidate(Throwable e, String bundleKey, String messageKey) {
        super(DEF_MSG, e, bundleKey, messageKey);
    }


    public BeenAccreditationPleaseCompleteTheDataCandidate(Throwable e, String messageKey) {
        super(DEF_MSG, e, BDL_KEY, messageKey);
    }


    public BeenAccreditationPleaseCompleteTheDataCandidate(Throwable e) {
        super(DEF_MSG, e, BDL_KEY, MSG_KEY);
    }


    public BeenAccreditationPleaseCompleteTheDataCandidate(String message, String bundleKey, String messageKey) {
        super(message, bundleKey, messageKey);
    }


    public BeenAccreditationPleaseCompleteTheDataCandidate(String message, String messageKey) {
        super(message, BDL_KEY, messageKey);
    }


    public BeenAccreditationPleaseCompleteTheDataCandidate(String message) {
        super(message, BDL_KEY, MSG_KEY);
    }


    public BeenAccreditationPleaseCompleteTheDataCandidate() {

        super(DEF_MSG, BDL_KEY, MSG_KEY);

    }
}
