package com.beshara.csc.hr.emp.business.shared.exception;


import com.beshara.csc.sharedutils.business.exception.SharedApplicationException;

public class EmployeeHiredBeforeException extends SharedApplicationException {


    /**
     *
     * @since 26/11/2015
     * @updatedBy TechnicalTeam [A.Agamy]
     * @Note added new constractors to pass exception
     * constructors generated by ExceptionHandlerProcessor
     */
    @SuppressWarnings("compatibility:-3161763639627883121")
    private static final long serialVersionUID = 1L;
    public static final String DEF_MSG = "EmployeeHiredBeforeException";
    public static final String MSG_KEY = "EmployeeHiredBeforeException";
    public static final String BDL_KEY = "EmployeeHiredBeforeException";

    public EmployeeHiredBeforeException(String message, Throwable e, String bundleKey, String messageKey) {
        super(message, e, bundleKey, messageKey);
    }


    public EmployeeHiredBeforeException(String message, Throwable e, String messageKey) {
        super(message, e, BDL_KEY, messageKey);
    }


    public EmployeeHiredBeforeException(String message, Throwable e) {
        super(message, e, BDL_KEY, MSG_KEY);
    }


    public EmployeeHiredBeforeException(Throwable e, String bundleKey, String messageKey) {
        super(DEF_MSG, e, bundleKey, messageKey);
    }


    public EmployeeHiredBeforeException(Throwable e, String messageKey) {
        super(DEF_MSG, e, BDL_KEY, messageKey);
    }


    public EmployeeHiredBeforeException(Throwable e) {
        super(DEF_MSG, e, BDL_KEY, MSG_KEY);
    }


    public EmployeeHiredBeforeException(String message, String bundleKey, String messageKey) {
        super(message, bundleKey, messageKey);
    }


    public EmployeeHiredBeforeException(String message, String messageKey) {
        super(message, BDL_KEY, messageKey);
    }


    public EmployeeHiredBeforeException() {
        super(DEF_MSG, BDL_KEY, MSG_KEY);
    }

    public EmployeeHiredBeforeException(String message) {

        super(message, BDL_KEY, MSG_KEY);

    }
}
