package com.beshara.csc.hr.emp.business.shared.exception;

import com.beshara.csc.sharedutils.business.exception.SharedApplicationException;

import javax.ejb.ApplicationException;

public class EmployeeServiceNotEndedException extends SharedApplicationException {


    /**
     *
     * @since 26/11/2015
     * @updatedBy TechnicalTeam [A.Agamy]
     * @Note added new constractors to pass exception
     * constructors generated by ExceptionHandlerProcessor
     */
    @SuppressWarnings("compatibility:-3350342573787259744")
    private static final long serialVersionUID = 1L;
    public static final String DEF_MSG = "EmployeeServiceNotEndedException";
    public static final String MSG_KEY = "EmployeeServiceNotEndedException";
    public static final String BDL_KEY = "EmployeeServiceNotEndedException";

    public EmployeeServiceNotEndedException(String message, Throwable e, String bundleKey, String messageKey) {
        super(message, e, bundleKey, messageKey);
    }


    public EmployeeServiceNotEndedException(String message, Throwable e, String messageKey) {
        super(message, e, BDL_KEY, messageKey);
    }


    public EmployeeServiceNotEndedException(String message, Throwable e) {
        super(message, e, BDL_KEY, MSG_KEY);
    }


    public EmployeeServiceNotEndedException(Throwable e, String bundleKey, String messageKey) {
        super(DEF_MSG, e, bundleKey, messageKey);
    }


    public EmployeeServiceNotEndedException(Throwable e, String messageKey) {
        super(DEF_MSG, e, BDL_KEY, messageKey);
    }


    public EmployeeServiceNotEndedException(Throwable e) {
        super(DEF_MSG, e, BDL_KEY, MSG_KEY);
    }


    public EmployeeServiceNotEndedException(String message, String bundleKey, String messageKey) {
        super(message, bundleKey, messageKey);
    }


    public EmployeeServiceNotEndedException(String message, String messageKey) {
        super(message, BDL_KEY, messageKey);
    }


    public EmployeeServiceNotEndedException() {
        super(DEF_MSG, BDL_KEY, MSG_KEY);
    }

    public EmployeeServiceNotEndedException(String message) {

        super(message, BDL_KEY, MSG_KEY);

    }
}
