package com.beshara.csc.hr.emp.business.shared.exception;

import javax.ejb.ApplicationException;


public class EmployeeNotHiredInMinException extends EmployeeNotHiredException {


    /**
     *
     * @since 26/11/2015
     * @updatedBy TechnicalTeam [A.Agamy]
     * @Note added new constractors to pass exception
     * constructors generated by ExceptionHandlerProcessor
     */
    @SuppressWarnings("compatibility:-4485906751177687898")
    private static final long serialVersionUID = 1L;
    public static final String DEF_MSG = "EmployeeNotHiredInMinException";
    public static final String MSG_KEY = "EmployeeNotHiredInMinException";
    public static final String BDL_KEY = "EmployeeNotHiredInMinException";

    public EmployeeNotHiredInMinException(String message, Throwable e, String bundleKey, String messageKey) {
        super(message, e, bundleKey, messageKey);
    }


    public EmployeeNotHiredInMinException(String message, Throwable e, String messageKey) {
        super(message, e, BDL_KEY, messageKey);
    }


    public EmployeeNotHiredInMinException(String message, Throwable e) {
        super(message, e, BDL_KEY, MSG_KEY);
    }


    public EmployeeNotHiredInMinException(Throwable e, String bundleKey, String messageKey) {
        super(DEF_MSG, e, bundleKey, messageKey);
    }


    public EmployeeNotHiredInMinException(Throwable e, String messageKey) {
        super(DEF_MSG, e, BDL_KEY, messageKey);
    }


    public EmployeeNotHiredInMinException(Throwable e) {
        super(DEF_MSG, e, BDL_KEY, MSG_KEY);
    }


    public EmployeeNotHiredInMinException(String message, String bundleKey, String messageKey) {
        super(message, bundleKey, messageKey);
    }


    public EmployeeNotHiredInMinException(String message, String messageKey) {
        super(message, BDL_KEY, messageKey);
    }


    public EmployeeNotHiredInMinException(String message) {

        super(message, BDL_KEY, MSG_KEY);

    }

    public EmployeeNotHiredInMinException() {

        super(DEF_MSG, BDL_KEY, MSG_KEY);

    }
}
