package com.beshara.csc.hr.emp.business.shared.exception;

import com.beshara.csc.sharedutils.business.exception.SharedApplicationException;

import javax.ejb.ApplicationException;

@ApplicationException(rollback = true)
public class ExperienceInsertionException extends SharedApplicationException {


    /**
     *
     * @since 26/11/2015
     * @updatedBy TechnicalTeam [A.Agamy]
     * @Note added new constractors to pass exception
     * constructors generated by ExceptionHandlerProcessor
     */
    @SuppressWarnings("compatibility:-4485906751177687898")
    private static final long serialVersionUID = 1L;
    public static final String DEF_MSG = "ExperienceInsertionException";
    public static final String MSG_KEY = "ExperienceInsertionException";
    public static final String BDL_KEY = "ExperienceInsertionException";

    public ExperienceInsertionException(String message, Throwable e, String bundleKey, String messageKey) {
        super(message, e, bundleKey, messageKey);
    }


    public ExperienceInsertionException(String message, Throwable e, String messageKey) {
        super(message, e, BDL_KEY, messageKey);
    }


    public ExperienceInsertionException(String message, Throwable e) {
        super(message, e, BDL_KEY, MSG_KEY);
    }


    public ExperienceInsertionException(Throwable e, String bundleKey, String messageKey) {
        super(DEF_MSG, e, bundleKey, messageKey);
    }


    public ExperienceInsertionException(Throwable e, String messageKey) {
        super(DEF_MSG, e, BDL_KEY, messageKey);
    }


    public ExperienceInsertionException(Throwable e) {
        super(DEF_MSG, e, BDL_KEY, MSG_KEY);
    }


    public ExperienceInsertionException(String message, String bundleKey, String messageKey) {
        super(message, bundleKey, messageKey);
    }


    public ExperienceInsertionException(String message, String messageKey) {
        super(message, BDL_KEY, messageKey);
    }


    public ExperienceInsertionException() {
        super(DEF_MSG, BDL_KEY, MSG_KEY);
    }

    public ExperienceInsertionException(String message) {

        super(message, BDL_KEY, MSG_KEY);

    }
}
