# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:  
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: allow long file names
      run: git config --system core.longpaths true
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8    
    - name: Build with Maven
      run: mvn -B package --file CSC/Phase1/Work_Stream_B/Code/DevCode/03-HR/EMP/Model/emp-jar_pom.xml
